### ISSUE TITLE
component which show text from Github tools(simplifiied, literal, TN,TW,TQ) 

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#112]
Примерный план
@foxprogs 
1. хук, который в который приходит массив с входными данными из базы, который идёт в гит и берёт необходимые ресурсы. К примеру 
[ 
  {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_rlob',
     commit: 6c733.......
     type: bible,
     format: usfm
     },
  {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_rsob',
     commit: 7c733.......,
     type: bible,
     format: usfm
     },
       {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_tn',
     commit: 6c733.......,
     type: tn,
     format: tsv
     }
 2. Функция - парсер, которая принимает файл и возвращает текст.
 3. Визуальное представление @RussLangMan  нам подскажет

**Comment by Valyukhov** [comment]
Примерный план
@foxprogs 
1. хук, который в который приходит массив с входными данными из базы, который идёт в гит и берёт необходимые ресурсы. К примеру 
[ 
  {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_rlob',
     commit: 6c733.......
     type: bible,
     format: usfm
     },
  {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_rsob',
     commit: 7c733.......,
     type: bible,
     format: usfm
     },
       {  bookId: 'tit',
     chapter: 4,
     resource: 'ru_gl/ru_tn',
     commit: 6c733.......,
     type: tn,
     format: tsv
     }
 2. Функция - парсер, которая принимает файл и возвращает текст.
 3. Визуальное представление @RussLangMan  нам подскажет

**Comment by foxprogs** [comment]
@Valyukhov мысли
1. Так как это гет запросы то мы можем использовать swr для получения данных. 
2. Так как они динамически не будут меняться - возможно стоит перенести это в getServerSideProps
3. Может быть не делать так чтобы одна функция получала все данные, а передавать элементы входного массива ниже в компонент. А компонент уже получает данные с сервера и правильно их отрисовывает
4. Парсер для юсфм, для маркдауна парсер не нужен

**Comment by Valyukhov** [comment]
@foxprogs 
мысли для usfm-rhl
`useGetChapterText(owner,repo,server,book,chapter, commit (если не указывать - берёт последний)`
```
return (
[ 
  {key:1, text:"Тит, продолжай напоминать нашим людям, что они должны быть послушны тем людям, которые имеют власть над ними. ... "},...вся глава
]
```

`useGetVersesText` - тоже самое , только определенные  стихи

**Comment by foxprogs** [comment]
@Valyukhov гуд
Вот только useGetVersesText это же будет просто `useGetChapterText().filter(verse => [6,7,8,9].includes(verse.key))`

ноутсы, истории, слова будут же в формате md. А что думаешь, если юсфм тоже в md перевести? Там есть несколько тегов, которые можно поддерживать: курсив, заголовки.

**Comment by Valyukhov** [comment]
1. Отображение
2. TN+TWL
![изображение](https://user-images.githubusercontent.com/74174349/188072318-89791371-bdc6-4b79-ac1c-4063fec96014.png)
3. TQ аккордеон
4. OBS опцию - скрывать картинки
