### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by foxprogs** [texttree/v-cana#125]
Сейчас мы блюрим через css, но по факту там стих остается. Что если мы блюр оставим, но вот внутри поменяем контент. Или сгенерируем текст, или сдвинем буквы или перемешаем. Чтобы размер строки не менялся и ничего не прыгало. Есть вот такая функция для shuffle 
```js
function shuffle (t)
{ let last = t.length
  let n
  while (last > 0)
  { n = rand(last)
    swap(t, n, --last)
  }
}

const rand = n =>
  Math.floor(Math.random() * n)

function swap (t, i, j)
{ let q = t[i]
  t[i] = t[j]
  t[j] = q
  return t
}
```
к примеру как-то так
verse.split(' ').map(el => shuffle(el)).join(' ')

**Comment by Valyukhov** [comment]
@foxprogs  ты же шафл предлагал уже )) а я только сейчас увидел
