### ISSUE TITLE
Book page

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#136]
![изображение](https://user-images.githubusercontent.com/74174349/193817710-20bb7fe3-b2a4-4ef5-abaa-86dd33521cad.png)
Сделать:
1. Выбор глав селектом.
2. Фетч с бд распределенных стихов
3. Кнопку начать перевод, если все стихи конкретной главы распределены и добавлены в бд

**Comment by Valyukhov** [comment]
@foxprogs почему переместил в done?
это же делать надо, то что Руслан просил

**Comment by foxprogs** [comment]
По картинке и описанию все вроде сделано @Valyukhov

**Comment by Valyukhov** [comment]
@foxprogs сделан только компонент распределения глав, а нужна страница книги(добавить на неё выбор главы) и в этом  компоненте, который на экране сделать вывод распределённых стихов, пока после обновления стейта вся сетка теряется

**Comment by Valyukhov** [comment]
ладно, надо новый просто ишью сделать
