### ISSUE TITLE
mistakes in text of agreement

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#160]
![изображение](https://user-images.githubusercontent.com/74174349/197214047-0f718345-13ce-47f0-a9ec-9f6735e10d7d.png)
 в некоторых местах пробелов нет
либо исправить либо запросить новый текст

**Comment by foxprogs** [comment]
Да, очень много косяков, проще запросить новый текст и br расставить или стилями переносы строки обработать (добавить класс `.whitespace-pre-line`)
