### ISSUE TITLE
Fix scroll

### ISSUE THREAD

**Issue by foxprogs** [texttree/v-cana#242]
На экране для планшета или телефона, когда у нас появляется скролл, прокрутка работает не корректно. Кажется такая же проблема была у нас и на обт. Он прокручивает не внутри дива а прокручивает страницу глобально. И по этому прыгает при переключении инструментов
![изображение](https://user-images.githubusercontent.com/30548361/202692874-7ecb3cf0-9de9-4aaf-86f7-b95e3c143417.png)

**Comment by Valyukhov** [comment]
#fixed
