### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by foxprogs** [texttree/v-cana#246]
Сделать так, чтобы после каждого обновления у юзеров открывалось окно, с текстом нового релиза
Как я вижу, как это должно работать
1. В хранилище записать, какая сейчас версия приложения. 
2. Если выходит обновление, то сравнить с тем что в хранилище. 
3. Если отличается то выдать модальное окно с описанием, что поменялось и добавилось.
4. Подумать о том, где и как брать изменения. Ченжлог приложения для разрабов и пользователей по идее отличается. Может завести какой-нить файл csv где мы будем фиксировать обновления для юзеров. И если версия виканы отличается, то брать разницу, и выдавать, что именно нового вышло. Либо не показывать только то что появилось с последней версии, а показывать ченжлог. А там пусть они сами читают.

**Comment by Pavel064** [comment]
![Image](https://github.com/texttree/v-cana/assets/60795829/707bb101-7369-484d-bd75-6e8b60c0df43)

- Обновить логотип
- в хедере номер версии, по нажатию на версию видим изменения версии. 
- нет всплывающих окон об обновлении.
- продублировать версию в сайдбар

**Comment by Pavel064** [comment]
комментарии:
- "Версия..." отображается только на начальном экране. Для авторизованного пользователя информация о версии доступна только в сайдбаре

**Comment by Pavel064** [comment]
![Image](https://github.com/texttree/v-cana/assets/60795829/c41c7134-f2f1-469d-b0b1-8fd7934f6d04)

**Comment by Pavel064** [comment]
![Image](https://github.com/texttree/v-cana/assets/60795829/71af98f2-32c0-4e7e-9bff-4710eda7246e)
