### ISSUE TITLE
Страница Авторизации

### ISSUE THREAD

**Issue by Sherzattv** [texttree/v-cana#33]
https://v-cana-design.netlify.app/login

* логин: qwerty
* пароль: 1234

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/e060d896-7494-4d9d-b123-203168982c71)

**Comment by Sherzattv** [comment]
- [ ] Бургер
- [ ] Лого ведет на главную страницу

**Comment by Sherzattv** [comment]
Кнопка "написать админу" работает если пользователь ввел не правильно свои данные

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/83eebf71-4b09-4a3c-89a6-60216a5d203a)

Вот так выглядит ошибка или все в порядке по цветам

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/cec8c3e7-5fd8-4519-a4df-e153e0e74351)

Когда поле правильно заполнено, обводка остается серой, можно ли по анологии с красным, обводку поле тоже сделать зеленым?

**Comment by Sherzattv** [comment]
https://www.figma.com/file/9QBRUNoBe01DMum1P3Cz4R/icon?node-id=0%3A1

Можно ли взять иконку бургера отсюда? и меня в фигме, все иконки отсюда в SVG

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/eead13c2-aa84-41c3-bf2c-5d41863df613)

Толщина у кнопки "Написать админу" стала больше, надо бы как у всех один размер

**Comment by Pavel064** [comment]
> 

исправлено

**Comment by Pavel064** [comment]
>

**Comment by Pavel064** [comment]
https://github.com/texttree/v-cana/issues/33#issuecomment-1131165562

исправлено

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/c8e864b6-9810-4f70-a0da-f3955d78df36)

Здесь какой зеленый ? Green?

**Comment by Pavel064** [comment]
везде идёт teal-зелёный;

рамка border-teal-600
окантовка рамки ring-teal-600

а вот когда инпут в фокусе, было focus:ring-teal-500, сейчас поправил на focus:ring-teal-600

**Comment by Sherzattv** [comment]
Для человека привычнее тут видеть Green, teal можно для остального UI оставить

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/65e0f8fd-41b2-4765-bb28-7669e871f935)

сделал так, постарался все учесть

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/f7c8a9cb-babe-49fb-a07d-897ad029ed67) 

добавил глазик)

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/67e7d7e6-1629-44d7-b4b1-064dabf6ef6c) 

Итог

**Comment by Sherzattv** [comment]
Убрать бургер)

**Comment by artyomchudakov** [comment]
Шер привет, 
можешь по конкретней написать, я не понял откуда его убрать именно, полностью со страницы с авторизацией или же в сайдбар, что я добавил кнопку бургера(которую по идее можно было бы иконкой Х заменить чтобы закрывать вообще сайдбар?


Еще было бы хорошо - если бы где-то палитра цветов, которые надо использовать в хэш формате #000000 была, чтобы с пипеткой не работать и не выискивать (например для сайдбар, там тоже со степенью прозрачности серый тон, но тыкая пипеткой все равно не выйдешь на тот же цвет и приходится потом сидеть и подбирать. А если это где-то уже прописано, то был бы рад получить ссылку на это. 


Еще было бы хорошо знать на какие размеры гаджетов ориентироваться в основном, то есть если адаптив настраивать, то как бы хотели бы чтобы на планшетах или телефонах выглядело?  


Если это заранее знать, то легче будет, чем делать сперва самому как думаешь, а потом вы посмотрите и скажите, а не  то - переделывать надо...

**Comment by foxprogs** [comment]
@artyomchudakov в основном пользователи с компа и ноутбука будут. Реже с планшета и ещё реже с телефона, так как там сложно всё разместить.

По поводу бокового меню - мы немного поспешили. То что есть сейчас было просто прототип. Самого дизайна утвержденного нет ещё. Оно будет появляться по нажатию на бургер. Остальное все думаю ещё не точно

**Comment by artyomchudakov** [comment]
> @artyomchudakov здесь где-то в issue есть ссылка на фигму с которой можно брать цвета. Бургер надо было убрать с этих страниц так как боковое меню есть только у тех юзеров, которые залогинились и поставили галочки в соглашении и символе веры. Адаптив делать так чтобы хорошо смотрелся с 360 до 1920.

да, это я уже тогда еще почти месяц назад уже в обсуждении с Пашей выяснил, и он или Тима убрали отображение бургера. 

Согласен, что логично, когда залогинился, потом предоставлять возможность видеть дополнительные навороты. На тот момент, когда этим занимался, тоже такая мысль возникала, но я просто делал, думая, что если так есть уже сейчас, значит так было оговорено у вас))
