### ISSUE TITLE
Кнопки соглашения

### ISSUE THREAD

**Issue by Sherzattv** [texttree/v-cana#38]
https://v-cana-design.netlify.app/agreements_home

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/4b00f063-8680-4796-8698-dca0f6f3a952)

Кнопки соглашения

**Comment by Sherzattv** [comment]
Каждая кнопка ведет на соглашения, след карточка

**Comment by Sherzattv** [comment]
Каждая кнопка ведет на соглашения, след карточка

**Comment by Pavel064** [comment]
а куда ведёт кнопка Далее?
