### ISSUE TITLE
Исповедание веры - описание

### ISSUE THREAD

**Issue by Sherzattv** [texttree/v-cana#40]
https://v-cana-design.netlify.app/confession_description

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/158482d2-37c6-43bf-b621-b4f9b971cf2b)

Там есть ссылка, ее нужно сделать активной, а кнопка ведет на полный текст

**Comment by Sherzattv** [comment]
![image.png](https://images.zenhubusercontent.com/6253ed242aaa45d4e3cea599/6d0ceb29-be3e-45f8-b946-4b8cd4e19fbb)

у меня почему то лого не поцентру

**Comment by Sherzattv** [comment]
и наверное на всех страницах уменьшить лого

**Comment by Pavel064** [comment]
@Sherzattv, всё исправили)

**Comment by Pavel064** [comment]
цвет текста ссылки: teal-500
