### ISSUE TITLE
isOpenSideBar state: do we need to use recoil?

### ISSUE THREAD

**Issue by Pavel064** [texttree/v-cana#444]
<img width="343" alt="image" src="https://github.com/texttree/v-cana/assets/60795829/ee27988c-4d20-4226-b559-d6b9098b3b3c">

Мы создаём состояние isOpenSideBar, которое используем в компоненте Layout (текущее состояние и сеттер), прокидываем в компонент AppBar (текущее состояние и сеттер), из AppBar прокидываем в SideBar (сеттер)

Вопрос: нужно ли использовать рекоил, или оставить, как есть?

**Comment by Valyukhov** [comment]
@Pavel064 I thnk - it's normal, because we use props for components, which are located nearby.
and the component through which we transmit the state also uses it.
It seems to me that we will not improve much in optimization, but there will only be more code.
To close
#close
