### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by Vorobushec** [texttree/v-cana#48]

**Comment by Vorobushec** [comment]
https://www.figma.com/file/7QjcXcwGI8SIaknFGN4wJl/vCana-prototype-v1.0?node-id=0%3A1

**Comment by artyomchudakov** [comment]
> @artyomchudakov вот ссылка на дизайн и на прототипы

спасибо, Паша мне скидывал потом тоже, после того, как у меня в начале много вопросов было. Эта ссылка у меня уже сохранена.

@foxprogs Вить, еще вопрос в целом, кто закрывает Issue, или кто решает, что закрывать? 

потому как есть вещи, которые уже сделаны (статус done), ну или в целом без описания какого либо (или как конкретно в этом случае, здесь в Issue просто хранится ссылка на figma, не было бы разве целесообразней в другое место перенести, в Readme или же в Zenhub куданибудь), но до сих пор висят в открытых Issue ? @Vorobushec что думаешь по этому поводу?

мне кажется, что по крайней мере меня отвлекает это в том плане, что кажется что  столько много еще открыто и нужно сделать, а заходишь и смотришь, либо сделано, либо не понятно что делать и зачем открыто еще ну и т.д.

**Comment by foxprogs** [comment]
@artyomchudakov После прогресса пулреквест вместе с закреплёнными за ним issue попадает на review, добавляешь несколько человек чтобы проверили, как только два approve получает то тот кто кодил может мерджить. PR и все issue попадают в done. А как только на спринт ревью мы все показали то переносим в closed
Если issue без описания то это просто запланированная задача, надо будет потом написать описание.
![изображение](https://user-images.githubusercontent.com/30548361/175495872-2615587e-356d-4a06-a2cb-0f9514c3e71f.png)
То что есть пару карточек с конфигами - просто решили здесь оставить. Это привычка с trello осталась.

**Comment by artyomchudakov** [comment]
спасибо, теперь более понятна структура и организация работы, что случается с PR & Issues, на каком этапе закрываются и тд. 

В каждой организации есть свои привычки и предпочтения, это нормально, но именно когда уже знаешь их сам, прочитал или объяснили, тогда много вещей легче понимать становится!
