### ISSUE TITLE
Export & Import Personal notes, Team notes and Dictionary

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#494]
Описание: создать возможность экспора и импорта заметок.
Формат - максимально удобный для экспорта. Учитывая что это будет служебный файл - то можно **json**.
Возможные проблемы, ососбенности:
1.Совместимость в разных компонентах.
Нужно ли чтобы файл экспорта можно было равнозначно подгрузить и в Personal Notes и в Team Notes и в Dictionary?
Или пользователя нужно обезопасить от него самого?

**Первый вариант** - экспорт как есть - равнозначная загрузка везде, валидировать только сами заметки(надо проверить словарь  - вроде одинаково всё).
**Второй вариант** - выгрузка c определенным ключом.
И помимо полей основных добавлять в json, который выгружается - тип.
к примеру таблица 
![изображение](https://github.com/texttree/v-cana/assets/74174349/965ab8a2-44e5-4f1c-97e5-e685228e44a2)
название у файла будет тогда по названию таблицы - team_notes_[датавыгрузки].json
сожержимое - либо линейное 
```
[
{id:'1'....type:'team_notes'}
{id:'2'....type:'team_notes'}
]
```
либо вложенное:
```
{
"type":team_notes,
"notes":
            [
              {id:'1'...}
              {id:'2'...}
             ]
}
```
я бы делал второй вариант, там один раз только указывать тип, но может первый будет удобней, практика покажет.
И в этом варианте - блокировать несовместивую загрузку на уровне валидации.
в апишке ты валидируешь, чтобы совпадали все ключи/типы значений, и сравниваешь тип - если пользователь пытается загрузить словарь в заметки - первая проверка на тип выдаст предупреждение - загружайте только заметки для team_note, и если тип  проверку проходит, тогда только валидировать сами заметки.

**Третий вариант**- отдать на выбор пользователя.
т.е. словарь конечно мы делаем как во втором варианте - потому что я не думаю, что у кого-то будет цель сохранить что-то в словарь и наоборот, если это не словарь
А вот взаимодействие тим ноутс и персонал ноутс можно спросить у пользователя
т.е. сначала валидировать заметки, если все ок - тогда если тип совпадает - сохранять как есть,
а если тип не совпадает, тогда спросить у пользователя - `вы точно хотите загрузить тим ноутс в персонал ноутс?`

2. История заметок и слов.
К примеру - человек делает экспорт, а потом делает ещё пару заметок или удаляет и хочет восстановить из экспортированного файла.
**Первый вариант** - просто заменять ( т.е. фактически удаляем всё из базы и вставляем новое).
**Второй вариант** - умная замена.
Проверяем все, и созданные новые и обновляем вместе с теми, которые восстанавливаются(тут скорей всего потеряется текст в уже созданных( т.е. если не удалил и не добавил, а текст просто поменял)
**Третий вариант** - умная замена с вопросом для пользователя. `У вас есть новые  заметки/слова с прошлого импорта, сохранить их?`
Тогда если да - второй вариант, если нет - первый.

English version:

Description: create the ability to export and import notes.
The format is the most convenient for export. Considering that this will be a service file, then you can **json**.
Possible problems, concerns:
1.Compatibility in different components.
Is it necessary that the export file can be loaded equally into Personal Notes, Team Notes, and Dictionary?
Or does the user need to be protected from himself?

**The first option ** - export as is - equivalent loading everywhere, validate only the notes themselves (you need to check the dictionary - everything seems to be the same).
**The second option** is unloading with a specific key.
And in addition to the main fields, add the type to the json that is being unloaded.
for example , the table
![изображение](https://github.com/texttree/v-cana/assets/74174349/965ab8a2-44e5-4f1c-97e5-e685228e44a2 )
the name of the file will then be based on the name of the table - team_notes_[upload date].json
refutable - either linear
``
[
{id:'1'....type:'team_notes'}
{id:'2'....type:'team_notes'}
]
``
or nested:
``
{
"type":team_notes,
"notes":
[
{id:'1'...}
{id:'2'...}
]
}
``
I would do the second option, there is only one time to specify the type, but maybe the first one will be more convenient, practice will show.
And in this case - block incompatible loading at the validation level.
in the app, you validate so that all keys /types of values match, and compare the type - if the user tries to load the dictionary into notes, the first type check will issue a warning - load only notes for team_note, and if the type passes the check, then only validate the notes themselves.

The third option is to give it to the user's choice.
that is, of course we do the dictionary as in the second option - because I don't think anyone will have a goal to save something to the dictionary and vice versa if it's not a dictionary
But the interaction of tim notes and the staff of the notes can be asked from the user
, i.e. first validate the notes, if everything is OK - then if the type matches - save as is,
and if the type does not match, then ask the user - `are you sure you want to upload tim notes to the staff of the notes?`

2. History of notes and words.
For example, a person makes an export, and then makes a couple more notes or deletes and wants to restore from the exported file.
The first option is simply to replace (i.e., we actually delete everything from the database and insert a new one).
The second option is a smart replacement.
We check everything, and the new ones created and update together with those that are being restored (here, most likely, the text in the already created ones will be lost (i.e. if you did not delete or add, but simply changed the text)
The third is a smart replacement with a question for the user. `Do you have new notes/words from the last import, save them?`
Then if yes - the second option, if not - the first.

**Comment by foxprogs** [comment]
@Valyukhov
1. я бы не позволял загружать словарь в личные заметки, и личные в командные. Пусть тип заметок все же будет как-то указан в файле экспорта. Да, можно руками там исправить и загрузить словарь в личные заметки, но это уже использование уровня pro.
2. по поводу имени файла - я бы в имени так же указал название проекта
3. по поводу структуры - согласен за второй вариант. Я бы даже чуть больше информации добавил в начало
```json
{
"info": {
    "type": "team_notes",
    "export_time": "",
    "project": "ru_rlob"
},
"data":
    [
        {"id":"1"}
        {"id":"2"}
    ]
}
```

4. По поводу умной замены, тут надо думать. Сравнивать время и айди старой заметки?
5. Не все поля надо экспортировать с базы. user_id и project_id точно не надо светить. Эти поля надо вставлять при импорте.
6. Надо подумать, на сколько безопасно экспортировать айдишники заметок. С одной стороны для parent_id они нужны. С другой стороны, ты переносишь из одного проекта заметки в другой. И как быть? Он смотрит, такой айди уже есть. И он не будет его добавлять? Но ведь этот айди с другого вообще проекта. Или личные заметки. Если сравнивать айди то можно вообще чужую заметку заменить. Получается что айди надо как-то заменять что ли. И тогда при импорте надо быть осторожным, чтобы не заменить чужую и чтобы сохранить parent_id. Я бы делал так. Сначала вставил все, у которых parent_id = null, получил новые айдишники родителей, и потом по структуре стал бы спускаться ниже, перезаписывая айди. Иначе он не даст создать ничего.

**Comment by Valyukhov** [comment]
@DenisArger @foxprogs 
Мысли по умному импорту.
Ещё у нас появился параметр, который надо учитывать - sorting, который необходим для умного ДНД
Тут возможно подскажет @Pavel064, он создавал алгоритм для фунцкии ДНД и для удаления/вставки заметок, которые учитывают этот параметр.

Какой может быть случай:
Если совпадают parent_id, либо parent_id is null, нужно те заметки, которые импортируются и соединяются с существующими - отсортировать. Может те, которые в базе уже есть, не трогать. А те, которые импортируются - сортировать, отталкиваясь от последнего сортинга существующих в базе.
Брать последний сортинг и вписывать
  - если => 0 то +1(папка непустая).
  - если нет - тогда первая - 0 и затем +1(папка пустая/либо заметок вообще нет)
  и конечно, при таком сортинге пропускать все, которые удалены( они у нас фактически не удаляются, в параметре deleted_at null меняется на дату удаления),

**Comment by foxprogs** [comment]
@DenisArger @Valyukhov я бы дописывал новые заметки просто в конец папки. Но как быть, если ты добавляешь заметки в папку из которой удалили заметки? Или к примеру переименовали ее? Ты будешь исправлять имя? 

По мне так тут получается очень много "если" и логики и исключений. 

К примеру когда ты закидываешь папку в папку в системе, он говорит переименовать или нет, если нет то он сравнивает имена файлов и спрашивает, переименовать или заменить? Я бы сделал по тому же принципу, но без вопросов.

Чуть выше я уже написал что будет проблема с айдишниками. Ты сделал с рлоба экспорт типноутсов и делаешь импорт в рсоб. Айдишники у всех заметок и папок уже существуют в базе, но они принадлежат другому проекту. По этому тебе нельзя тут просто спросить, заменить или нет. Тебе придется переписать все айдишники.
