### ISSUE TITLE
[User Story]: Make user story for place where user can download Desktop version Level

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#689]
1. Where user can download
2. What kind of version - last, Windows/Linux, List versions or automatically scan OS ang suggest version.
3. Add empty app without projects or adding 1 test project

**Comment by RussLangMan** [comment]
https://docs.google.com/document/d/1xcM1q_Dt3NgFFq7_GRaA4rTUsqWOgmlbegVX75vISTk/edit

**Comment by RussLangMan** [comment]
Текст для страницы с загрузкой

Спасибо за выбор десктоп-версии V-CANA! В настоящий момент программа доступна только для операционной системы Windows. После установки вы сможете работать с проектами по переводу Библии в режиме офлайн. В программе также будет доступен тестовый проект, чтобы вы могли ознакомиться с её возможностями.

Инструкции:
1. Скачайте установочный файл, нажав на ссылку ниже.
2. Запустите файл и следуйте инструкциям установщика.
3. После установки откройте программу, чтобы изучить тестовый проект и ознакомиться с платформой.

Приятной работы с V-CANA! Следите за обновлениями и новыми версиями для других операционных систем.

**Скачать V-CANA Desktop**


Thank you for choosing the V-CANA desktop version! Currently available for Windows, this version allows you to work on Bible translation projects offline. After installation, you'll have access to a test project within the program to explore its features.

Instructions:

1. Download the installation file by clicking the link below.
2. Run the file and follow the installation prompts.
3. Once installed, open the program to explore the test project and familiarize yourself with the platform.

We hope you enjoy using V-CANA! Stay tuned for updates and future releases for other operating systems.

**Download V-CANA Desktop**

¡Gracias por elegir la versión de escritorio de V-CANA! Actualmente, el programa está disponible solo para el sistema operativo Windows. Después de la instalación, podrás trabajar en proyectos de traducción bíblica sin conexión. Además, dentro del programa estará disponible un proyecto de prueba para que puedas explorar sus características.

Instrucciones:

1. Descarga el archivo de instalación haciendo clic en el enlace de abajo.
2. Ejecuta el archivo y sigue las indicaciones del instalador.
3. Una vez instalada, abre el programa para explorar el proyecto de prueba y familiarizarte con la plataforma.

¡Disfruta usando V-CANA! Mantente al tanto de las actualizaciones y futuras versiones para otros sistemas operativos.

**Descargar V-CANA Desktop**

**Comment by Valyukhov** [comment]
@RussLangMan нужно доработать, у нас поменялось название - LEVEL или Level
