### ISSUE TITLE
change the colors of the button of the selected language

### ISSUE THREAD

**Issue by Vorobushec** [texttree/v-cana#76]

**Comment by Vorobushec** [comment]
Кнопка выбранного языка интерфейся подсвечивается ярче, чем кнопка невыбранного языка

**Comment by artyomchudakov** [comment]
@Vorobushec я просмотрел твой комментарий, все настроено по идее правильно. Но при запуске, если ты проводишь комунду yarn dev  то попадаешь сразу на вот эту ссылку http://localhost:3000/en, то есть загружается **en** версия  по умолчанию, и поэтому кнопка RU подсвечивается ярче. 
Посмотри, у тебя такое же поведение на компе и ответил ли я на твой вопрос?

**Comment by foxprogs** [comment]
@artyomchudakov У тебя браузер на другом языке по этому скорее всего английская версия открывается. У нас русская.
