### ISSUE TITLE
wrap all await in try/catch

### ISSUE THREAD

**Issue by foxprogs** [texttree/v-cana#93]
Обернуть все await вызовы, чтобы обрабатывать нормально все ответы, и особенно ошибки, например так:
```js
try {
  const { user, error } = await supabaseService.auth.api.createUser({
    email,
    password,
  })
  if (error) throw error
} catch (error) {
  res.status(404).json({ error })
  return
}
res.status(200).json(user)
````

**Comment by Valyukhov** [comment]
@foxprogs 
вот такие вызовы тоже обрабатывать c помощью try?
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  }
}

**Comment by foxprogs** [comment]
> @foxprogs вот такие вызовы тоже обрабатывать c помощью try? export async function getStaticProps({ locale }) { return { props: { ...(await serverSideTranslations(locale, ['common'])), // Will be passed to the page component as props }, } } https://github.com/texttree/v-cana/blob/feature-50/pages/agreements.js


@Valyukhov не, это вроде не надо
